#!/bin/bash

pip install datasets transformers evaluate
wget https://raw.githubusercontent.com/awesome-release/AI-Examples/main/pytorch/tune.py

python3 tune.py || true

# Allow logs to finish outputting.
sleep 30
echo "Done."
