#!/usr/bin/env python3

import argparse
from nemo.deploy import NemoQuery

def main():
    parser = argparse.ArgumentParser(description="Query a Nemo model.")
    parser.add_argument("prompt", type=str, help="The prompt to send to the model.")
    parser.add_argument("--max_output_token", type=int, default=190, help="Maximum number of output tokens.")
    parser.add_argument("--top_k", type=int, default=1, help="Top K sampling.")
    parser.add_argument("--top_p", type=float, default=0.0, help="Top P sampling.")
    parser.add_argument("--temperature", type=float, default=1.0, help="Temperature for sampling.")
    parser.add_argument("--model_name", type=str, default="release-fine-tuned-peft", help="The name of the model to query.")

    args = parser.parse_args()

    nq = NemoQuery(url="localhost:8000", model_name=args.model_name)
    output = nq.query_llm(
        prompts=[args.prompt],
        max_output_token=args.max_output_token,
        top_k=args.top_k,
        top_p=args.top_p,
        temperature=args.temperature
    )
    
    # Ensure new lines are properly formatted in the output
    formatted_output = ''.join(output[0]).replace('\\n', '\n')

    # Remove repeated question if it appears at the start of the response
    if formatted_output.startswith(args.prompt):
        formatted_output = formatted_output[len(args.prompt):]
    
    print("Query: ", args.prompt)
    print("Response: ", formatted_output)

if __name__ == "__main__":
    main()

