#!/bin/bash

# Converts HF Llama to .nemo

set -e

MODELS_ROOT_PATH=${MODELS_ROOT_PATH:-"/bucket/ai-models-tmp"}

# Setting default values for environment variables if not already set
export MODEL="${MODEL:-${MODELS_ROOT_PATH}/llama-2-7b-hf.nemo}"

# If passed a folder rather than a .nemo file, convert it to nemo
if [ -d $MODEL ]; then
  export MODEL_FOLDER_NAME=$(basename $MODEL)
  export NEMO_MODEL_FILE_NAME={$MODEL_FOLDER_NAME}".nemo"
  echo "===== Copying model: aws s3 cp $RAW_MODEL_PATH /workspace/$MODEL_FOLDER_NAME"
  aws s3 cp $RAW_MODEL_PATH /workspace/$MODEL_FOLDER_NAME --recursive
  echo "===== Converting HF model .nemo format"
  python /opt/NeMo/scripts/nlp_language_modeling/convert_hf_llama_to_nemo.py --in-file=/workspace/$MODEL_FOLDER_NAME --out-file=/workspace/$NEMO_MODEL_FILE_NAME
  echo "===== Converted HF model to .nemo!"
  # Store the .nemo file in s3
  echo "===== Storing .nemo model to s3"
  aws s3 cp /workspace/$NEMO_MODEL_FILE_NAME $MODELS_ROOT_PATH/$NEMO_MODEL_FILE_NAME
  echo "===== Done writing .nemo to s3"
fi
