#!/bin/bash

: ${FINE_TUNED_CHECKPOINT_PATH:?FINE_TUNED_CHECKPOINT_PATH must be set}

TRITON_DEPLOY_SCRIPT_PATH=${TRITON_DEPLOY_SCRIPT_PATH:-"/opt/NeMo/scripts/deploy/deploy_triton.py"}
TRITON_MODEL_NAME=${TRITON_MODEL_NAME:-"release-fine-tuned-peft"}

if [ ! -f ${FINE_TUNED_CHECKPOINT_PATH} ]; then
  echo "Checkpoint not found: ${FINE_TUNED_CHECKPOINT_PATH}"
  exit 1
fi

python \
  ${TRITON_DEPLOY_SCRIPT_PATH} \
  --nemo_checkpoint ${FINE_TUNED_CHECKPOINT_PATH} \
  --model_type="llama" \
  --triton_model_name ${TRITON_MODEL_NAME}
