---
auto_deploy: true
context: release-ry6clz
domain: ai-playground.releaseapp.io
repo_name: releasehub-com/AI-Examples
resources:
  memory:
    limits: 64Gi
    requests: 16Gi
  cpu:
    limits: 128
    requests: 12
  replicas: 1
shared_volumes:
  - name: workspace
    size: 40Gi
    type: persistent
  - name: tmp
    size: 40Gi
    type: persistent
jobs:
  - name: peft-tuning
    command:
      - "/bin/peft_tuning"
    from_services: nemofw-training
    completed_timeout: 10800
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/tmp"
      - claim: workspace
        mount_path: "/workspace"
services:
  - name: nemofw-training
    image: ai-examples/nemofw-training
    has_repo: true
    build:
      context: "."
      dockerfile: Dockerfile
    command:
      - "/bin/peft_tuning"
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/workspace"
    cpu:
      limits: 48
      requests: 12
    memory:
      limits: 64Gi
      requests: 16Gi
workflows:
  - name: setup
    parallelize:
      - step: fine-tune
        tasks:
          - jobs.peft-tuning
        halt_on_error: true
  - name: teardown
    parallelize:
      - step: remove-environment
        tasks:
          - release.remove_environment
tracking_branch: peft
environment_templates:
  - name: permanent
  - name: ephemeral
