---
auto_deploy: true
context: release-ry6clz
domain: ai-playground.releaseapp.io
repo_name: releasehub-com/AI-Examples
resources:
  cpu:
    limits: 48
    requests: 30
  memory:
    limits: 192Gi
    requests: 120Gi
  replicas: 1
shared_volumes:
  - name: workspace
    size: 40Gi
    type: persistent
  - name: tmp
    size: 40Gi
    type: persistent
jobs:
  - name: peft-tuning
    command:
      - "curl"
      - "-sfL"
      - "https://raw.githubusercontent.com/awesome-release/AI-Examples/main/scripts/peft_tuning"
      - "|"
      - "bash"
      - "-"
    from_services: nemofw-training
    completed_timeout: 10800
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/tmp"
      - claim: workspace
        mount_path: "/workspace"
  - name: triton-export
    command:
      - "curl"
      - "-sfL"
      - "https://raw.githubusercontent.com/awesome-release/AI-Examples/main/scripts/export"
      - "|"
      - "bash"
      - "-"
    from_services: nemofw-inference
    completed_timeout: 3600
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/tmp"
      - claim: workspace
        mount_path: "/workspace"
services:
  - name: nemofw-training
    image: nvcr.io/ea-bignlp/ga-participants/nemofw-training:23.08.03
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/workspace"
  - name: nemofw-inference
    image: nvcr.io/ea-bignlp/ga-participants/nemofw-inference:23.10_fix_v2
    node_selector:
      - key: nvidia.com/gpu
        value: "true"
      - key: beta.kubernetes.io/instance-type
        value: "g5.12xlarge"
    volumes:
      - name: shmem
        type: shmem
        size: 16Gi
        mount_path: "/dev/shm"
      - claim: tmp
        mount_path: "/workspace"
workflows:
  - name: setup
    parallelize:
      - step: fine-tune
        tasks:
          - jobs.peft-tuning
        halt_on_error: true
      - step: triton-export
        tasks:
          - jobs.triton-export
        halt_on_error: true
  - name: teardown
    parallelize:
      - step: remove-environment
        tasks:
          - release.remove_environment
tracking_branch: peft
environment_templates:
  - name: permanent
  - name: ephemeral
