#!/bin/bash

printf "\n\n===== Copying model to bucket...\n"
export DATE=$(date +'%Y-%m-%d-%H-%M-%S')
mkdir $OUT_DIR/axolotol-out-$DATE
cp /storage/tune.yml $OUT_DIR/axolotol-out-$DATE/
printenv > $OUT_DIR/axolotol-out-$DATE/.env
cp -R /storage/lora-out/ $OUT_DIR/axolotol-out-$DATE/

printf "\n\n===== Copying merged model to bucket...\n"
cp -R /storage/lora-out/merged $OUT_DIR/axolotol-out-$DATE/

printf "\n\n==== Converting to ollama format...\n"
python3 examples/convert_legacy_llama.py /storage/merged --outtype f16 --outfile /storage/ollama.bin

printf "\n\n==== Quantizing model...\n"
./llama-quantize /storage/ollama.bin /storage/ollama-quantized.bin q4_0

printf "\n\n===== Copying ollama formatted models to bucket...\n"
cp -R /storage/ollama.bin $OUT_DIR/axolotol-out-$DATE/ollama.bin
cp -R /storage/ollama-quantized.bin $OUT_DIR/axolotol-out-$DATE/ollama-quantized.bin

cat > $OUT_DIR/axolotol-out-$DATE/Modelfile <<- EOM
FROM ollama.bin
TEMPLATE "[INST] <<SYS>>{{ .System }}<</SYS>>
{{ .Prompt }} [/INST]"
EOM

if [[ -z "${OLLAMA_BASE_URL}" ]]; then
  echo ""
else
  echo "\n\n===== Creating model in Ollama server $OLLAMA_BASE_URL"
  curl ${OLLAMA_BASE_URL}api/create -d "{
    \"name\": \"axolotol-out-$DATE\",
    \"modelfile\": \"FROM $OUT_DIR/axolotol-out-$DATE/ollama.bin\nTEMPLATE \"[INST] <<SYS>>{{ .System }}<</SYS>>\n{{ .Prompt }} [/INST]\"\"
  }"
fi

printf "\n\n===== DONE!\n\n"
