#!/bin/bash

if [[ $MODEL_TYPE == "llama2" ]]; then
  curl -sfL https://raw.githubusercontent.com/awesome-release/AI-Examples/main/axolotl/llama2 | bash -
elif [[ $MODEL_TYPE == "llama3" ]]; then
  curl -sfL https://raw.githubusercontent.com/awesome-release/AI-Examples/main/axolotl/llama3 | bash - 
else
  echo "Unsupported model type: $MODEL_TYPE"
fi
